services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5433:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    image: api-grocery:1.0.3
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - api_grocery_images:/usr/src/app/src/images
    depends_on:
      - db

volumes:
  postgres_data:
  api_grocery_images:
